"""Behave environment hooks for migrated-project.

Generated by behave-gen. Add before/after hooks for scenario, feature, and
all run lifecycle events as needed.
"""

from __future__ import annotations


def before_all(context) -> None:
    """Called once before any feature runs."""


def after_all(context) -> None:
    """Called once after all features have run."""


def before_feature(context, feature) -> None:
    """Called before each feature."""


def after_feature(context, feature) -> None:
    """Called after each feature."""


def before_scenario(context, scenario) -> None:
    """Called before each scenario."""


def after_scenario(context, scenario) -> None:
    """Called after each scenario."""
