"""``behave-gen update`` command implementation.

Upgrades an existing project's generated artifacts (environment.py, step
libraries, and templates) to the latest behave-gen versions. The update is
idempotent and non-destructive: it only overwrites files that were previously
generated by behave-gen, leaving user-authored code untouched.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

from behave_gen.commands.environment import AddEnvironmentOptions, add_environment
from behave_gen.commands.steps import AddStepsOptions, add_steps


class UpdateError(Exception):
    """User-facing error raised by ``update``."""


@dataclass(frozen=True, slots=True)
class UpdateReport:
    """Outcome of an update run."""

    updated: tuple[str, ...] = field(default_factory=tuple)
    skipped: tuple[str, ...] = field(default_factory=tuple)
    warnings: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True, slots=True)
class UpdateOptions:
    """Options for ``update``."""

    force: bool = False
    kit: bool = False
    data: bool = False


_BEHAVE_GEN_MARKER = "Generated by behave-gen"


def _is_generated(path: Path) -> bool:
    """Return True if ``path`` was generated by behave-gen (marker check)."""
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    return _BEHAVE_GEN_MARKER in text


def _update_step_libraries(root: Path, force: bool) -> tuple[list[str], list[str], list[str]]:
    """Re-apply built-in step libraries that already exist in the project."""
    updated: list[str] = []
    skipped: list[str] = []
    warnings: list[str] = []
    steps_dir = root / "features" / "steps"
    if not steps_dir.is_dir():
        return updated, skipped, warnings

    library_files = {
        "http": "http_steps.py",
        "auth": "auth_steps.py",
    }
    for lib, filename in library_files.items():
        target = steps_dir / filename
        if not target.exists():
            continue
        if not force and not _is_generated(target):
            skipped.append(str(target.relative_to(root)))
            warnings.append(
                f"Skipped {target.relative_to(root)}: not a behave-gen file. "
                "Use --force to override."
            )
            continue
        try:
            # Remove and re-add to get the latest template.
            target.unlink()
            add_steps(root, AddStepsOptions(lib=lib))
            updated.append(str(target.relative_to(root)))
        except Exception as exc:  # noqa: BLE001 - surface update failures cleanly.
            warnings.append(f"Failed to update {target.relative_to(root)}: {exc}")
    return updated, skipped, warnings


def _update_environment(root: Path, options: UpdateOptions) -> tuple[list[str], list[str]]:
    """Re-apply the environment.py template if it was generated."""
    updated: list[str] = []
    warnings: list[str] = []
    env_file = root / "environment.py"
    if not env_file.exists():
        return updated, warnings
    if not options.force and not _is_generated(env_file):
        warnings.append("Skipped environment.py: not a behave-gen file. Use --force to override.")
        return updated, warnings
    try:
        add_environment(root, AddEnvironmentOptions(kit=options.kit, data=options.data))
        updated.append("environment.py")
    except Exception as exc:  # noqa: BLE001 - surface update failures cleanly.
        warnings.append(f"Failed to update environment.py: {exc}")
    return updated, warnings


def run_update(
    options: UpdateOptions,
    project_root: str | Path | None = None,
) -> int:
    """CLI entry point for ``behave-gen update``."""
    root = Path(project_root) if project_root is not None else Path.cwd()
    if not root.is_dir():
        print(f"update: Project root not found: {root}", file=sys.stderr)
        return 1

    all_updated: list[str] = []
    all_skipped: list[str] = []
    all_warnings: list[str] = []

    env_updated, env_warnings = _update_environment(root, options)
    all_updated.extend(env_updated)
    all_warnings.extend(env_warnings)

    steps_updated, steps_skipped, steps_warnings = _update_step_libraries(root, options.force)
    all_updated.extend(steps_updated)
    all_skipped.extend(steps_skipped)
    all_warnings.extend(steps_warnings)

    for path in all_updated:
        print(f"Updated {path}")
    for path in all_skipped:
        print(f"Skipped {path}", file=sys.stderr)
    for warning in all_warnings:
        print(f"update: warning: {warning}", file=sys.stderr)

    if not all_updated and not all_skipped:
        print("Nothing to update. No behave-gen generated files found.")
    else:
        print(f"\nUpdated {len(all_updated)} file(s).")
    return 0
