"""``behave-gen update`` command implementation.

Upgrades an existing project's generated artifacts (environment.py, step
libraries, and templates) to the latest behave-gen versions. The update is
idempotent and non-destructive: it only overwrites files that were previously
generated by behave-gen, leaving user-authored code untouched.
"""

from __future__ import annotations

import contextlib
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from behave_gen.commands.environment import AddEnvironmentOptions, add_environment
from behave_gen.commands.steps import AddStepsOptions, add_steps
from behave_gen.config import BehaveGenConfig
from behave_gen.paths import resolve_project_root
from behave_gen.project import Project, ProjectError


class UpdateError(Exception):
    """User-facing error raised by ``update``."""


@dataclass(frozen=True, slots=True)
class UpdateReport:
    """Outcome of an update run."""

    updated: tuple[str, ...] = field(default_factory=tuple)
    skipped: tuple[str, ...] = field(default_factory=tuple)
    warnings: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True, slots=True)
class UpdateOptions:
    """Options for ``update``."""

    force: bool = False
    kit: bool = False
    data: bool = False


_BEHAVE_GEN_MARKER = "Generated by behave-gen"


def _is_generated(path: Path) -> bool:
    """Return True if ``path`` was generated by behave-gen (marker check).

    Symlinks are never considered generated to avoid reading files outside the
    project root through a symlink.
    """
    if path.is_symlink() or not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return _BEHAVE_GEN_MARKER in text


def _remove_target_safely(target: Path, root: Path) -> str | None:
    """Remove ``target`` if it is a generated file or symlink.

    Returns an error message if the target cannot be removed, otherwise None.
    """
    try:
        is_dir = target.is_dir()
        is_symlink = target.is_symlink()
    except OSError as exc:
        return f"Could not inspect {target}: {exc}"
    if is_dir and not is_symlink:
        try:
            label = str(target.relative_to(root))
        except ValueError:
            label = target.name
        return f"{label} is a directory; skipping"
    try:
        target.unlink(missing_ok=True)
    except OSError as exc:
        return f"Could not remove {target}: {exc}"
    return None


def _update_step_libraries(project: Project, force: bool) -> tuple[list[str], list[str], list[str]]:
    """Re-apply built-in step libraries that already exist in the project."""
    updated: list[str] = []
    skipped: list[str] = []
    warnings: list[str] = []
    steps_dir = project.steps_dir
    if not steps_dir.is_dir():
        return updated, skipped, warnings

    library_files = {
        "http": "http_steps.py",
        "auth": "auth_steps.py",
    }
    for lib, filename in library_files.items():
        target = steps_dir / filename
        if not target.exists() and not target.is_symlink():
            continue
        if not force and not _is_generated(target):
            rel = target.relative_to(project.root)
            skipped.append(str(rel))
            warnings.append(f"Skipped {rel}: not a behave-gen file. Use --force to override.")
            continue

        error = _remove_target_safely(target, project.root)
        if error:
            rel = target.relative_to(project.root)
            warnings.append(f"Failed to update {rel}: {error}")
            continue

        tmp_path = steps_dir / f".update-{uuid.uuid4().hex}.tmp"
        try:
            add_steps(
                project.root,
                AddStepsOptions(lib=lib),
                steps_dir=steps_dir,
                output_file=tmp_path,
            )
            tmp_path.replace(target)
            updated.append(str(target.relative_to(project.root)))
        except Exception as exc:  # noqa: BLE001 - surface update failures cleanly.
            rel = target.relative_to(project.root)
            warnings.append(f"Failed to update {rel}: {exc}")
        finally:
            with contextlib.suppress(OSError):
                tmp_path.unlink(missing_ok=True)
    return updated, skipped, warnings


def _update_environment(project: Project, options: UpdateOptions) -> tuple[list[str], list[str]]:
    """Re-apply the environment.py template if it was generated."""
    updated: list[str] = []
    warnings: list[str] = []
    env_file = project.environment_file
    if not env_file.exists() and not env_file.is_symlink():
        return updated, warnings
    if not options.force and not _is_generated(env_file):
        warnings.append("Skipped environment.py: not a behave-gen file. Use --force to override.")
        return updated, warnings

    error = _remove_target_safely(env_file, project.root)
    if error:
        warnings.append(f"Failed to update environment.py: {error}")
        return updated, warnings

    try:
        add_environment(
            project.root,
            AddEnvironmentOptions(kit=options.kit, data=options.data),
            environment_file=project.environment_file,
        )
        updated.append("environment.py")
    except Exception as exc:  # noqa: BLE001 - surface update failures cleanly.
        warnings.append(f"Failed to update environment.py: {exc}")
    return updated, warnings


def run_update(
    options: UpdateOptions,
    project_root: str | Path | None = None,
    *,
    config: BehaveGenConfig | None = None,
) -> int:
    """CLI entry point for ``behave-gen update``."""
    root = resolve_project_root(project_root)
    try:
        project = Project.from_root(root, config=config)
    except ProjectError as exc:
        print(f"update: {exc}", file=sys.stderr)
        return 1

    all_updated: list[str] = []
    all_skipped: list[str] = []
    all_warnings: list[str] = []

    env_updated, env_warnings = _update_environment(project, options)
    all_updated.extend(env_updated)
    all_warnings.extend(env_warnings)

    steps_updated, steps_skipped, steps_warnings = _update_step_libraries(project, options.force)
    all_updated.extend(steps_updated)
    all_skipped.extend(steps_skipped)
    all_warnings.extend(steps_warnings)

    for path in all_updated:
        print(f"Updated {path}")
    for path in all_skipped:
        print(f"Skipped {path}", file=sys.stderr)
    for warning in all_warnings:
        print(f"update: warning: {warning}", file=sys.stderr)

    if not all_updated and not all_skipped:
        print("Nothing to update. No behave-gen generated files found.")
    else:
        print(f"\nUpdated {len(all_updated)} file(s).")
    return 0
