"""Sample step definitions for $project_name.

Generated by behave-gen. These steps make ``features/sample.feature``
runnable; remove them together with the feature once real tests exist.
"""

from __future__ import annotations

from typing import Any

from behave import given, then, when


@given("a precondition holds")
def step_precondition(context: Any) -> None:
    """Set up the sample precondition."""
    context.precondition = True


@when("an action is performed")
def step_action(context: Any) -> None:
    """Perform the sample action."""
    context.action_done = context.precondition


@then("the outcome is observed")
def step_outcome(context: Any) -> None:
    """Assert the sample outcome."""
    assert context.action_done
