"""E2E: ``add environment`` → ``add config`` → ``update``.

Verifies that environment.py rewriting, ecosystem package configuration, and
the update workflow work correctly on a generated project.
"""

from __future__ import annotations

from pathlib import Path

from behave_gen.commands.environment import (
    AddEnvironmentOptions,
    add_environment,
    run_add_config,
)
from behave_gen.commands.steps import AddStepsOptions, add_steps
from behave_gen.commands.update import UpdateOptions, run_update

from .conftest import run_behave_dry_run, run_ruff_check


class TestAddEnvironment:
    """``add environment`` rewrites environment.py with kit/data wiring."""

    def test_kit_wiring(self, project: Path) -> None:
        add_environment(project, AddEnvironmentOptions(kit=True))
        env = (project / "environment.py").read_text(encoding="utf-8")
        assert "behave_kit" in env
        assert "setup_kit" in env

    def test_data_wiring(self, project: Path) -> None:
        add_environment(project, AddEnvironmentOptions(data=True))
        env = (project / "environment.py").read_text(encoding="utf-8")
        assert "behave_data" in env
        assert "setup_data" in env

    def test_kit_and_data_wiring(self, project: Path) -> None:
        add_environment(project, AddEnvironmentOptions(kit=True, data=True))
        env = (project / "environment.py").read_text(encoding="utf-8")
        assert "behave_kit" in env
        assert "behave_data" in env

    def test_environment_passes_ruff(self, project: Path) -> None:
        add_environment(project, AddEnvironmentOptions(kit=True, data=True))
        proc = run_ruff_check(project, "environment.py")
        assert proc.returncode == 0, f"ruff failed:\n{proc.stdout}\n{proc.stderr}"

    def test_environment_passes_behave_dry_run(self, project: Path) -> None:
        add_environment(project, AddEnvironmentOptions(kit=True, data=True))
        proc = run_behave_dry_run(project)
        assert proc.returncode == 0, f"behave --dry-run failed:\n{proc.stdout}\n{proc.stderr}"


class TestAddConfig:
    """``add config`` adds ecosystem packages to pyproject.toml."""

    def test_add_kit_config(self, project: Path) -> None:
        rc = run_add_config("behave-kit", project_root=project)
        assert rc == 0
        pyproject = (project / "pyproject.toml").read_text(encoding="utf-8")
        assert "behave-kit" in pyproject

    def test_add_data_config(self, project: Path) -> None:
        rc = run_add_config("behave-data", project_root=project)
        assert rc == 0
        pyproject = (project / "pyproject.toml").read_text(encoding="utf-8")
        assert "behave-data" in pyproject

    def test_add_config_idempotent(self, project: Path) -> None:
        run_add_config("behave-kit", project_root=project)
        rc = run_add_config("behave-kit", project_root=project)
        assert rc == 0

    def test_add_unknown_config_returns_one(self, project: Path) -> None:
        rc = run_add_config("nonexistent", project_root=project)
        assert rc == 1


class TestUpdate:
    """``update`` re-applies step libraries to generated files."""

    def test_update_refreshes_http_steps(self, project: Path) -> None:
        add_steps(project, AddStepsOptions(lib="http"))
        # Modify the file to simulate user edits.
        steps_file = project / "features" / "steps" / "http_steps.py"
        original = steps_file.read_text(encoding="utf-8")
        steps_file.write_text(original + "\n# user comment\n", encoding="utf-8")

        rc = run_update(UpdateOptions(force=True), project_root=project)
        assert rc == 0
        updated = steps_file.read_text(encoding="utf-8")
        assert "# user comment" not in updated
        assert "Generated by behave-gen" in updated

    def test_update_skips_non_generated_files(self, project: Path) -> None:
        add_steps(project, AddStepsOptions(lib="http"))
        steps_file = project / "features" / "steps" / "http_steps.py"
        # Remove the marker to simulate a user-created file.
        content = steps_file.read_text(encoding="utf-8").replace(
            "Generated by behave-gen", "Custom"
        )
        steps_file.write_text(content, encoding="utf-8")

        rc = run_update(UpdateOptions(force=False), project_root=project)
        assert rc == 0
        # File should not be overwritten.
        assert "Custom" in steps_file.read_text(encoding="utf-8")

    def test_update_no_step_libraries(self, project: Path) -> None:
        rc = run_update(UpdateOptions(), project_root=project)
        assert rc == 0
