"""Tests for built-in step library helpers."""

from __future__ import annotations

from behave_gen.step_libraries import build_http_step_module, http_template


def test_http_template_contains_marker() -> None:
    source = http_template()
    assert "Generated by behave-gen" in source
    assert "$project_name" in source


def test_build_http_step_module_renders_project_name() -> None:
    rendered = build_http_step_module(project_name="demo")
    assert '"""HTTP step definitions for demo.' in rendered


def test_build_http_step_module_escapes_quotes_and_backslashes() -> None:
    # A malicious-looking name with quotes and backslashes must still produce valid
    # Python source, not break the module docstring or syntax.
    rendered = build_http_step_module(project_name='demo"project\\path')
    assert '"""HTTP step definitions for demo\\"project\\\\path.' in rendered
