"""Tests for ``behave-gen update``."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from behave_gen.cli.app import app
from behave_gen.commands.init import InitOptions, init_project
from behave_gen.commands.steps import AddStepsOptions, add_steps
from behave_gen.commands.update import UpdateOptions, run_update

runner = CliRunner()


def _make_project(tmp_path: Path) -> Path:
    return init_project(tmp_path, InitOptions(name="proj"))


def test_update_missing_root_returns_one(tmp_path: Path) -> None:
    assert run_update(UpdateOptions(), project_root=tmp_path / "nope") == 1


def test_update_no_generated_files(tmp_path: Path) -> None:
    root = _make_project(tmp_path)
    # Remove generated environment.py and sample feature.
    (root / "environment.py").unlink()
    code = run_update(UpdateOptions(), project_root=root)
    assert code == 0


def test_update_regenerates_environment(tmp_path: Path) -> None:
    root = _make_project(tmp_path)
    # environment.py is generated by init, so it has the marker.
    code = run_update(UpdateOptions(), project_root=root)
    assert code == 0
    assert (root / "environment.py").is_file()


def test_update_regenerates_step_libraries(tmp_path: Path) -> None:
    root = _make_project(tmp_path)
    add_steps(root, AddStepsOptions(lib="http"))
    code = run_update(UpdateOptions(), project_root=root)
    assert code == 0
    assert (root / "features" / "steps" / "http_steps.py").is_file()
    content = (root / "features" / "steps" / "http_steps.py").read_text(encoding="utf-8")
    assert "Generated by behave-gen" in content


def test_update_skips_user_modified_files(tmp_path: Path) -> None:
    root = _make_project(tmp_path)
    add_steps(root, AddStepsOptions(lib="http"))
    steps_file = root / "features" / "steps" / "http_steps.py"
    # Remove the marker to simulate user-authored code.
    content = steps_file.read_text(encoding="utf-8").replace(
        "Generated by behave-gen.", "User-authored."
    )
    steps_file.write_text(content, encoding="utf-8")
    code = run_update(UpdateOptions(), project_root=root)
    assert code == 0
    # File should not have been overwritten.
    new_content = steps_file.read_text(encoding="utf-8")
    assert "User-authored." in new_content


def test_update_force_overwrites_user_files(tmp_path: Path) -> None:
    root = _make_project(tmp_path)
    add_steps(root, AddStepsOptions(lib="http"))
    steps_file = root / "features" / "steps" / "http_steps.py"
    content = steps_file.read_text(encoding="utf-8").replace(
        "Generated by behave-gen.", "User-authored."
    )
    steps_file.write_text(content, encoding="utf-8")
    code = run_update(UpdateOptions(force=True), project_root=root)
    assert code == 0
    new_content = steps_file.read_text(encoding="utf-8")
    assert "Generated by behave-gen." in new_content


def test_update_cli(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _make_project(tmp_path)
    monkeypatch.chdir(root)
    result = runner.invoke(app, ["update"])
    assert result.exit_code == 0, result.output


def test_update_cli_force(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _make_project(tmp_path)
    monkeypatch.chdir(root)
    result = runner.invoke(app, ["update", "--force"])
    assert result.exit_code == 0, result.output


def test_update_with_kit_data(tmp_path: Path) -> None:
    root = _make_project(tmp_path)
    code = run_update(UpdateOptions(kit=True, data=True), project_root=root)
    assert code == 0
    content = (root / "environment.py").read_text(encoding="utf-8")
    assert "behave_kit" in content
    assert "behave_data" in content
