"""Behave environment hooks for $project_name (with behave-data).

Generated by behave-gen. behave-data provides typed data tables and data
hooks. See https://github.com/behave/behave-data for details.
"""

from __future__ import annotations

from behave_data import setup_data


def before_all(context) -> None:
    """Wire behave-data hooks before any feature runs."""
    setup_data(context)


def after_all(context) -> None:
    """Run once after all features have run."""


def before_feature(context, feature) -> None:
    """Run before each feature."""


def after_feature(context, feature) -> None:
    """Run after each feature."""


def before_scenario(context, scenario) -> None:
    """Run before each scenario."""


def after_scenario(context, scenario) -> None:
    """Run after each scenario."""
