"""Behave environment hooks for $project_name (with behave-kit).

Generated by behave-gen. behave-kit provides fixtures and soft assertion
helpers. See https://github.com/behave/behave-kit for details.
"""

from __future__ import annotations

from behave_kit import setup as setup_kit


def before_all(context) -> None:
    """Wire behave-kit fixtures before any feature runs."""
    setup_kit(context)


def after_all(context) -> None:
    """Run once after all features have run."""


def before_feature(context, feature) -> None:
    """Run before each feature."""


def after_feature(context, feature) -> None:
    """Run after each feature."""


def before_scenario(context, scenario) -> None:
    """Run before each scenario."""


def after_scenario(context, scenario) -> None:
    """Run after each scenario."""
