"""Behave environment hooks for $project_name (with behave-data).

Generated by behave-gen. behave-data provides typed data tables and data
hooks. See https://github.com/behave/behave-data for details.
"""

from __future__ import annotations

from behave_data import setup_data


def before_all(context) -> None:
    """Called once before any feature runs; wires behave-data hooks."""
    setup_data(context)


def after_all(context) -> None:
    """Called once after all features have run."""


def before_feature(context, feature) -> None:
    """Called before each feature."""


def after_feature(context, feature) -> None:
    """Called after each feature."""


def before_scenario(context, scenario) -> None:
    """Called before each scenario."""


def after_scenario(context, scenario) -> None:
    """Called after each scenario."""
